version: "3.9"
services:
  app:
    build:
      context: .
    container_name: website
    restart: always
    volumes:
      - app:/var/www/html
    ports:
      - "8085:80"
    links:
      - mysql-server
  
  mysql-server:
    image: mysql/mysql-server:latest
    restart: always
    environment:
      MYSQL_DATABASE: toolingdb
      MYSQL_USER: mysql_user
      MYSQL_PASSWORD: '1234ABC'
      MYSQL_ROOT_PASSWORD: '1234abc'
    ports:
      - "3306:3306"
    volumes:
      - mysql-server:/var/lib/mysql

volumes:
  app:
  mysql-server: