version: "3.7"
services:
  web-server:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: website
    restart: always
    volumes:
      - "./html/:/var/www/html/"
    ports:
      - "8085:80"
    links: mysql-server
  
  mysql-server:
    image: mysql/mysql-server:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234abc
    ports:
      - "3306:3306"