version: "3.9"
services:
  db:
    image: mysql/mysql-server:latest
    hostname: mysqlserverhost
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: toolingdb
      MYSQL_USER: mysql_user
      MYSQL_PASSWORD: '1234ABC'
      MYSQL_ROOT_PASSWORD: '1234abc'
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - db:/var/lib/mysql

  app:
    build:
      context: .
    container_name: website
    restart: unless-stopped
    volumes:
      - ~/html/.:/var/www/html
    ports:
      - "${APP_PORT}:80"
    links:
      - db
    depends_on:
      - db
  
    

# volumes:
#   app:
#   db: